//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMContexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMContexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXUI.Localization.CRMContexResources", typeof(CRMContexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad Id.
        /// </summary>
        public static string Ciudad_CiudadId {
            get {
                return ResourceManager.GetString("Ciudad_CiudadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Ciudad_Nombre {
            get {
                return ResourceManager.GetString("Ciudad_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Ciudad_Provincia {
            get {
                return ResourceManager.GetString("Ciudad_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad Db Set.
        /// </summary>
        public static string CiudadPlural {
            get {
                return ResourceManager.GetString("CiudadPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Id.
        /// </summary>
        public static string Claim_ClaimId {
            get {
                return ResourceManager.GetString("Claim_ClaimId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        public static string Claim_ClaimType {
            get {
                return ResourceManager.GetString("Claim_ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value.
        /// </summary>
        public static string Claim_ClaimValue {
            get {
                return ResourceManager.GetString("Claim_ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Claim_User {
            get {
                return ResourceManager.GetString("Claim_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Db Set.
        /// </summary>
        public static string ClaimPlural {
            get {
                return ResourceManager.GetString("ClaimPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Cliente_Ciudad {
            get {
                return ResourceManager.GetString("Cliente_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Id.
        /// </summary>
        public static string Cliente_ClienteId {
            get {
                return ResourceManager.GetString("Cliente_ClienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion Sector.
        /// </summary>
        public static string Cliente_DescripcionSector {
            get {
                return ResourceManager.GetString("Cliente_DescripcionSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Cliente_Direccion {
            get {
                return ResourceManager.GetString("Cliente_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Cliente_Division {
            get {
                return ResourceManager.GetString("Cliente_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Cliente_Email {
            get {
                return ResourceManager.GetString("Cliente_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Nacimiento.
        /// </summary>
        public static string Cliente_FechaNacimiento {
            get {
                return ResourceManager.GetString("Cliente_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Cliente_Nombre {
            get {
                return ResourceManager.GetString("Cliente_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Cliente_Provincia {
            get {
                return ResourceManager.GetString("Cliente_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruc.
        /// </summary>
        public static string Cliente_Ruc {
            get {
                return ResourceManager.GetString("Cliente_Ruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Cliente_Sector {
            get {
                return ResourceManager.GetString("Cliente_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Cliente_Telefono {
            get {
                return ResourceManager.GetString("Cliente_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono Convencional.
        /// </summary>
        public static string Cliente_TelefonoConvencional {
            get {
                return ResourceManager.GetString("Cliente_TelefonoConvencional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Cliente_Vendedor {
            get {
                return ResourceManager.GetString("Cliente_Vendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor Id.
        /// </summary>
        public static string Cliente_VendedorId {
            get {
                return ResourceManager.GetString("Cliente_VendedorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string ClientePlural {
            get {
                return ResourceManager.GetString("ClientePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Contacto_Cargo {
            get {
                return ResourceManager.GetString("Contacto_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Contacto_Celular {
            get {
                return ResourceManager.GetString("Contacto_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Contacto_Cliente {
            get {
                return ResourceManager.GetString("Contacto_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Id.
        /// </summary>
        public static string Contacto_ContactoId {
            get {
                return ResourceManager.GetString("Contacto_ContactoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Contacto_Email {
            get {
                return ResourceManager.GetString("Contacto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Nacimiento.
        /// </summary>
        public static string Contacto_FechaNacimiento {
            get {
                return ResourceManager.GetString("Contacto_FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Contacto_Nombre {
            get {
                return ResourceManager.GetString("Contacto_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma Decision.
        /// </summary>
        public static string Contacto_TomaDecision {
            get {
                return ResourceManager.GetString("Contacto_TomaDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Db Set.
        /// </summary>
        public static string ContactoPlural {
            get {
                return ResourceManager.GetString("ContactoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Etapa {
            get {
                return ResourceManager.GetString("Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Etapa_Descripcion {
            get {
                return ResourceManager.GetString("Etapa_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa Id.
        /// </summary>
        public static string Etapa_EtapaId {
            get {
                return ResourceManager.GetString("Etapa_EtapaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porciento.
        /// </summary>
        public static string Etapa_Porciento {
            get {
                return ResourceManager.GetString("Etapa_Porciento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas.
        /// </summary>
        public static string EtapaPlural {
            get {
                return ResourceManager.GetString("EtapaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login.
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Id.
        /// </summary>
        public static string ExternalLogin_ExternalLoginId {
            get {
                return ResourceManager.GetString("ExternalLogin_ExternalLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Provider.
        /// </summary>
        public static string ExternalLogin_LoginProvider {
            get {
                return ResourceManager.GetString("ExternalLogin_LoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Key.
        /// </summary>
        public static string ExternalLogin_ProviderKey {
            get {
                return ResourceManager.GetString("ExternalLogin_ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ExternalLogin_User {
            get {
                return ResourceManager.GetString("ExternalLogin_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Db Set.
        /// </summary>
        public static string ExternalLoginPlural {
            get {
                return ResourceManager.GetString("ExternalLoginPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencia.
        /// </summary>
        public static string Gerencia {
            get {
                return ResourceManager.GetString("Gerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Gerencia_Apellidos {
            get {
                return ResourceManager.GetString("Gerencia_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Url.
        /// </summary>
        public static string Gerencia_ImagenUrl {
            get {
                return ResourceManager.GetString("Gerencia_ImagenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Gerencia_Nombre {
            get {
                return ResourceManager.GetString("Gerencia_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Gerencia_Nuevo {
            get {
                return ResourceManager.GetString("Gerencia_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupacion.
        /// </summary>
        public static string Gerencia_Ocupacion {
            get {
                return ResourceManager.GetString("Gerencia_Ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Id.
        /// </summary>
        public static string Gerencia_PerfilId {
            get {
                return ResourceManager.GetString("Gerencia_PerfilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencia.
        /// </summary>
        public static string GerenciaPlural {
            get {
                return ResourceManager.GetString("GerenciaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea Negocio.
        /// </summary>
        public static string LineaNegocio {
            get {
                return ResourceManager.GetString("LineaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string LineaNegocio_Descripcion {
            get {
                return ResourceManager.GetString("LineaNegocio_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea Negocio Id.
        /// </summary>
        public static string LineaNegocio_LineaNegocioId {
            get {
                return ResourceManager.GetString("LineaNegocio_LineaNegocioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea Negocios.
        /// </summary>
        public static string LineaNegocioPlural {
            get {
                return ResourceManager.GetString("LineaNegocioPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidad.
        /// </summary>
        public static string Oportunidad {
            get {
                return ResourceManager.GetString("Oportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asesor.
        /// </summary>
        public static string Oportunidad_Asesor {
            get {
                return ResourceManager.GetString("Oportunidad_Asesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Oportunidad_Cantidad {
            get {
                return ResourceManager.GetString("Oportunidad_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Oportunidad_Cliente {
            get {
                return ResourceManager.GetString("Oportunidad_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Venta.
        /// </summary>
        public static string Oportunidad_ContactoVenta {
            get {
                return ResourceManager.GetString("Oportunidad_ContactoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Oportunidad_Etapa {
            get {
                return ResourceManager.GetString("Oportunidad_Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectativa Asesor.
        /// </summary>
        public static string Oportunidad_ExpectativaAsesor {
            get {
                return ResourceManager.GetString("Oportunidad_ExpectativaAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectativa Venta.
        /// </summary>
        public static string Oportunidad_ExpectativaVenta {
            get {
                return ResourceManager.GetString("Oportunidad_ExpectativaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string Oportunidad_FechaInicio {
            get {
                return ResourceManager.GetString("Oportunidad_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Prevista Cierre.
        /// </summary>
        public static string Oportunidad_FechaPrevistaCierre {
            get {
                return ResourceManager.GetString("Oportunidad_FechaPrevistaCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea Negocio.
        /// </summary>
        public static string Oportunidad_LineaNegocio {
            get {
                return ResourceManager.GetString("Oportunidad_LineaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Oportunidad_Nombre {
            get {
                return ResourceManager.GetString("Oportunidad_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidad Id.
        /// </summary>
        public static string Oportunidad_OportunidadId {
            get {
                return ResourceManager.GetString("Oportunidad_OportunidadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potencial.
        /// </summary>
        public static string Oportunidad_Potencial {
            get {
                return ResourceManager.GetString("Oportunidad_Potencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Oportunidad_Producto {
            get {
                return ResourceManager.GetString("Oportunidad_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVU.
        /// </summary>
        public static string Oportunidad_PVU {
            get {
                return ResourceManager.GetString("Oportunidad_PVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cartera.
        /// </summary>
        public static string Oportunidad_TipoCartera {
            get {
                return ResourceManager.GetString("Oportunidad_TipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Gestion.
        /// </summary>
        public static string Oportunidad_TipoGestion {
            get {
                return ResourceManager.GetString("Oportunidad_TipoGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomador Desicion.
        /// </summary>
        public static string Oportunidad_TomadorDesicion {
            get {
                return ResourceManager.GetString("Oportunidad_TomadorDesicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidad Ds Db Set.
        /// </summary>
        public static string OportunidadPlural {
            get {
                return ResourceManager.GetString("OportunidadPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Perfil_Apellidos {
            get {
                return ResourceManager.GetString("Perfil_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Url.
        /// </summary>
        public static string Perfil_ImagenUrl {
            get {
                return ResourceManager.GetString("Perfil_ImagenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Perfil_Nombre {
            get {
                return ResourceManager.GetString("Perfil_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupacion.
        /// </summary>
        public static string Perfil_Ocupacion {
            get {
                return ResourceManager.GetString("Perfil_Ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Id.
        /// </summary>
        public static string Perfil_PerfilId {
            get {
                return ResourceManager.GetString("Perfil_PerfilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pefil Dbset.
        /// </summary>
        public static string PerfilPlural {
            get {
                return ResourceManager.GetString("PerfilPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Producto_Nombre {
            get {
                return ResourceManager.GetString("Producto_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto Id.
        /// </summary>
        public static string Producto_ProductoId {
            get {
                return ResourceManager.GetString("Producto_ProductoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productoes.
        /// </summary>
        public static string ProductoPlural {
            get {
                return ResourceManager.GetString("ProductoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Provincia_Nombre {
            get {
                return ResourceManager.GetString("Provincia_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia Id.
        /// </summary>
        public static string Provincia_ProvinciaId {
            get {
                return ResourceManager.GetString("Provincia_ProvinciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provicia Db Set.
        /// </summary>
        public static string ProvinciaPlural {
            get {
                return ResourceManager.GetString("ProvinciaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string Role_RoleId {
            get {
                return ResourceManager.GetString("Role_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Db Set.
        /// </summary>
        public static string RolePlural {
            get {
                return ResourceManager.GetString("RolePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string Tarea {
            get {
                return ResourceManager.GetString("Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignado A.
        /// </summary>
        public static string Tarea_AsignadoA {
            get {
                return ResourceManager.GetString("Tarea_AsignadoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado Por.
        /// </summary>
        public static string Tarea_CreadoPor {
            get {
                return ResourceManager.GetString("Tarea_CreadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Tarea_Descripcion {
            get {
                return ResourceManager.GetString("Tarea_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Tarea_Fecha {
            get {
                return ResourceManager.GetString("Tarea_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cumplimiento.
        /// </summary>
        public static string Tarea_FechaCumplimiento {
            get {
                return ResourceManager.GetString("Tarea_FechaCumplimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Tarea_Identificador {
            get {
                return ResourceManager.GetString("Tarea_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Estado.
        /// </summary>
        public static string Tarea_TareaEstado {
            get {
                return ResourceManager.GetString("Tarea_TareaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Id.
        /// </summary>
        public static string Tarea_TareaId {
            get {
                return ResourceManager.GetString("Tarea_TareaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Historial.
        /// </summary>
        public static string TareaHistorial {
            get {
                return ResourceManager.GetString("TareaHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string TareaHistorial_Descripcion {
            get {
                return ResourceManager.GetString("TareaHistorial_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string TareaHistorial_Fecha {
            get {
                return ResourceManager.GetString("TareaHistorial_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string TareaHistorial_Tarea {
            get {
                return ResourceManager.GetString("TareaHistorial_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Estado.
        /// </summary>
        public static string TareaHistorial_TareaEstado {
            get {
                return ResourceManager.GetString("TareaHistorial_TareaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Historial Id.
        /// </summary>
        public static string TareaHistorial_TareaHistorialId {
            get {
                return ResourceManager.GetString("TareaHistorial_TareaHistorialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Historials.
        /// </summary>
        public static string TareaHistorialPlural {
            get {
                return ResourceManager.GetString("TareaHistorialPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Db Set.
        /// </summary>
        public static string TareaPlural {
            get {
                return ResourceManager.GetString("TareaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Gestion.
        /// </summary>
        public static string TipoGestion {
            get {
                return ResourceManager.GetString("TipoGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string TipoGestion_Descripcion {
            get {
                return ResourceManager.GetString("TipoGestion_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Gestion Id.
        /// </summary>
        public static string TipoGestion_TipoGestionId {
            get {
                return ResourceManager.GetString("TipoGestion_TipoGestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Gestions.
        /// </summary>
        public static string TipoGestionPlural {
            get {
                return ResourceManager.GetString("TipoGestionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Hash.
        /// </summary>
        public static string User_PasswordHash {
            get {
                return ResourceManager.GetString("User_PasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string User_Perfil {
            get {
                return ResourceManager.GetString("User_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stamp.
        /// </summary>
        public static string User_SecurityStamp {
            get {
                return ResourceManager.GetString("User_SecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string User_UserId {
            get {
                return ResourceManager.GetString("User_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Db Set.
        /// </summary>
        public static string UserPlural {
            get {
                return ResourceManager.GetString("UserPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Vendedor_Apellidos {
            get {
                return ResourceManager.GetString("Vendedor_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Url.
        /// </summary>
        public static string Vendedor_ImagenUrl {
            get {
                return ResourceManager.GetString("Vendedor_ImagenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Vendedor_Nombre {
            get {
                return ResourceManager.GetString("Vendedor_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupacion.
        /// </summary>
        public static string Vendedor_Ocupacion {
            get {
                return ResourceManager.GetString("Vendedor_Ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Id.
        /// </summary>
        public static string Vendedor_PerfilId {
            get {
                return ResourceManager.GetString("Vendedor_PerfilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presuspuesto Asignado.
        /// </summary>
        public static string Vendedor_PresuspuestoAsignado {
            get {
                return ResourceManager.GetString("Vendedor_PresuspuestoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string VendedorPlural {
            get {
                return ResourceManager.GetString("VendedorPlural", resourceCulture);
            }
        }
    }
}
